jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      id: setup-ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
name: TarsosDSP Gradle Build
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
permissions:
  contents: read
